---
- hosts: routers
  gather_facts: false
  connection: local
  tasks:
  - name: show run
    ios_command:
      commands:
      - sh run
    register: shrun
  - name: Report information
    debug:
      var: shrun
  
