---
- hosts: routers
  gather_facts: false
  connection: local
  tasks:
  - name: Configure static route
    ios_static_route:
      prefix: 0.0.0.0 
      mask: 0.0.0.0
      next_hop: s0/0/0

  - name: configure hostname
    ios_config:
      lines: hostname {{ inventory_hostname }}
 
  - name: configure domain
    ios_system:
      lookup-enabled: no
  
