---
- hosts: web
  tasks:
  - name: Check if file exists
    stat: path=/tmp/hosts
    register: hosts_file
  - name: report status
    debug:
      var: hosts_file.stat.exists
  - name: Copy file
    copy: src=/etc/hosts dest=/tmp/hosts
    when: hosts_file.stat.exists == false
