---
- hosts: all
  tasks: 
  - name: Make folder under tmp directory
    file: 
      dest: /tmp/ans
      state: directory
  - name: Create sample file for all systems
    file: 
      dest: /tmp/ans/all-file
      state: touch
    tags: create
  - name: Create sample file for all systems
    file:
      dest: /tmp/ans/all-file
      state: absent
    tags: remove
